trigger: none

pool:
  vmImage: 'macos-latest'

steps:

- task: IconBadge@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/samples'
    contents: '**/*.jpg'
    bannerVersionNamePosition: 'bottomLeft'
    bannerVersionNameText: 'Beta'

- task: IconBadge@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/samples'
    contents: '**/*.svg'
    bannerVersionNamePosition: 'topLeft'
    bannerVersionNameText: 'Alpha'
    bannerVersionNumberPosition: 'bottom'
    bannerVersionNumberText: '1.2.3'
    bannerVersionNumberColor: '#E3C73C'
    bannerVersionNumberTextColor: '#FFFFFF'

- task: IconBadge@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/samples'
    contents: '**/*.png'
    bannerVersionNamePosition: 'topRight'
    bannerVersionNameText: 'Debug'
    bannerVersionNumberPosition: 'center'
    bannerVersionNumberText: '12.34.567'

- task: IconBadge@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/samples'
    bannerVersionNamePosition: 'bottomRight'
    bannerVersionNameText: 'Prerelease'
    bannerVersionNumberPosition: 'top'
    bannerVersionNumberText: '1.0.0.0'
    bannerVersionNumberTextColor: '#E3C73C'

- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/samples/**'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'